# Read the Docs configuration file for MkDocs projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_create_environment:
      # Устанавливаем Poetry
      # Смотрите https://python-poetry.org/docs/#installing-manually
      - pip install poetry
    post_install:
      # Устанавливаем зависимости с помощью Poetry.
      # Если у вас есть группа зависимостей для документации (например, [tool.poetry.group.docs]), используйте --with docs
      # VIRTUAL_ENV нужно устанавливать вручную пока что
      # Смотрите https://github.com/readthedocs/readthedocs.org/pull/11152/
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

mkdocs:
  configuration: mkdocs.yml

# Секция python:install:requirements больше не нужна, так как Poetry будет управлять зависимостями
# python:
#   install:
#   - requirements: docs/requirements.txt
